services:
  arca-postgres:
    image: postgres:16
    container_name: arca-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: arca_db
      POSTGRES_USER: arca_user
      POSTGRES_PASSWORD: arca_password
    ports:
      - "5433:5432"
    volumes:
      - arca_postgres_data:/var/lib/postgresql/data

volumes:
  arca_postgres_data: