BEGIN;

DROP TABLE IF EXISTS resgates CASCADE;
DROP TABLE IF EXISTS denuncias CASCADE;
DROP TABLE IF EXISTS castracoes CASCADE;
DROP TABLE IF EXISTS adocoes CASCADE;
DROP TABLE IF EXISTS animais CASCADE;
DROP TABLE IF EXISTS tutores CASCADE;

CREATE TABLE tutores (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY,

                         nome VARCHAR(150) NOT NULL,
                         cpf CHAR(11) NOT NULL,
                         telefone VARCHAR(20) NOT NULL,
                         email VARCHAR(120),
                         senha_hash VARCHAR(255) NOT NULL,
                         data_nascimento DATE NOT NULL,

                         criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                         CONSTRAINT pk_tutores PRIMARY KEY (id),

                         CONSTRAINT uq_tutores_cpf UNIQUE (cpf),

                         CONSTRAINT ck_tutores_nome_tamanho
                             CHECK (LENGTH(TRIM(nome)) >= 3),

                         CONSTRAINT ck_tutores_cpf_formato
                             CHECK (cpf ~ '^[0-9]{11}$'),

    CONSTRAINT ck_tutores_telefone_formato
        CHECK (telefone ~ '^\([0-9]{2}\) 9[0-9]{4}-[0-9]{4}$'),

    CONSTRAINT ck_tutores_email_formato
        CHECK (
            email IS NULL
            OR email ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$'
        ),

    CONSTRAINT ck_tutores_data_nascimento_valida
        CHECK (data_nascimento <= CURRENT_DATE),

    CONSTRAINT ck_tutores_datas_validas
        CHECK (atualizado_em >= criado_em)
);

CREATE UNIQUE INDEX uq_tutores_email_lower
    ON tutores (LOWER(email))
    WHERE email IS NOT NULL;


CREATE TABLE animais (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY,

                         nome VARCHAR(100) NOT NULL,
                         especie VARCHAR(20) NOT NULL,
                         raca VARCHAR(100) NOT NULL,
                         sexo VARCHAR(10) NOT NULL,
                         idade_aproximada VARCHAR(50) NOT NULL,
                         local_resgate VARCHAR(150) NOT NULL,
                         status VARCHAR(30) NOT NULL,

                         criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                         CONSTRAINT pk_animais PRIMARY KEY (id),

                         CONSTRAINT ck_animais_nome_tamanho
                             CHECK (LENGTH(TRIM(nome)) >= 2),

                         CONSTRAINT ck_animais_especie
                             CHECK (especie IN ('Cachorro', 'Gato')),

                         CONSTRAINT ck_animais_raca_tamanho
                             CHECK (LENGTH(TRIM(raca)) >= 2),

                         CONSTRAINT ck_animais_sexo
                             CHECK (sexo IN ('Macho', 'Fêmea')),

                         CONSTRAINT ck_animais_idade_aproximada
                             CHECK (idade_aproximada ~ '^[0-9]+ (meses|anos)$'),

    CONSTRAINT ck_animais_local_resgate_tamanho
        CHECK (LENGTH(TRIM(local_resgate)) >= 3),

    CONSTRAINT ck_animais_status
        CHECK (status IN ('Disponível', 'Adotado', 'Em tratamento')),

    CONSTRAINT ck_animais_datas_validas
        CHECK (atualizado_em >= criado_em)
);


CREATE TABLE adocoes (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY,

                         tutor_id BIGINT NOT NULL,
                         animal_id BIGINT NOT NULL,

                         data_adocao DATE NOT NULL DEFAULT CURRENT_DATE,
                         status VARCHAR(30) NOT NULL,
                         observacoes TEXT,

                         criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                         CONSTRAINT pk_adocoes PRIMARY KEY (id),

                         CONSTRAINT fk_adocoes_tutor
                             FOREIGN KEY (tutor_id)
                                 REFERENCES tutores(id)
                                 ON UPDATE CASCADE
                                 ON DELETE RESTRICT,

                         CONSTRAINT fk_adocoes_animal
                             FOREIGN KEY (animal_id)
                                 REFERENCES animais(id)
                                 ON UPDATE CASCADE
                                 ON DELETE RESTRICT,

                         CONSTRAINT uq_adocoes_tutor_animal
                             UNIQUE (tutor_id, animal_id),

                         CONSTRAINT ck_adocoes_status
                             CHECK (status IN ('Solicitada', 'Aprovada', 'Recusada', 'Cancelada')),

                         CONSTRAINT ck_adocoes_data_valida
                             CHECK (data_adocao <= CURRENT_DATE),

                         CONSTRAINT ck_adocoes_observacoes_tamanho
                             CHECK (
                                 observacoes IS NULL
                                     OR LENGTH(TRIM(observacoes)) >= 5
                                 ),

                         CONSTRAINT ck_adocoes_datas_validas
                             CHECK (atualizado_em >= criado_em)
);

CREATE UNIQUE INDEX uq_adocoes_animal_aprovada
    ON adocoes (animal_id)
    WHERE status = 'Aprovada';


CREATE TABLE castracoes (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY,

                            tutor_id BIGINT NOT NULL,

                            especie VARCHAR(20) NOT NULL,
                            raca VARCHAR(100) NOT NULL,
                            sexo VARCHAR(10) NOT NULL,
                            localizacao VARCHAR(180) NOT NULL,
                            observacoes TEXT,
                            status VARCHAR(30) NOT NULL,
                            data_solicitacao DATE NOT NULL DEFAULT CURRENT_DATE,

                            criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                            CONSTRAINT pk_castracoes PRIMARY KEY (id),

                            CONSTRAINT fk_castracoes_tutor
                                FOREIGN KEY (tutor_id)
                                    REFERENCES tutores(id)
                                    ON UPDATE CASCADE
                                    ON DELETE RESTRICT,

                            CONSTRAINT ck_castracoes_especie
                                CHECK (especie IN ('Cachorro', 'Gato')),

                            CONSTRAINT ck_castracoes_raca_tamanho
                                CHECK (LENGTH(TRIM(raca)) >= 2),

                            CONSTRAINT ck_castracoes_sexo
                                CHECK (sexo IN ('Macho', 'Fêmea')),

                            CONSTRAINT ck_castracoes_localizacao_tamanho
                                CHECK (LENGTH(TRIM(localizacao)) >= 3),

                            CONSTRAINT ck_castracoes_status
                                CHECK (status IN ('Solicitada', 'Agendada', 'Realizada', 'Cancelada')),

                            CONSTRAINT ck_castracoes_data_valida
                                CHECK (data_solicitacao <= CURRENT_DATE),

                            CONSTRAINT ck_castracoes_observacoes_tamanho
                                CHECK (
                                    observacoes IS NULL
                                        OR LENGTH(TRIM(observacoes)) >= 5
                                    ),

                            CONSTRAINT ck_castracoes_datas_validas
                                CHECK (atualizado_em >= criado_em)
);


CREATE TABLE denuncias (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY,

                           tutor_id BIGINT,
                           tipo_denuncia VARCHAR(50) NOT NULL,
                           descricao TEXT NOT NULL,
                           localizacao VARCHAR(180) NOT NULL,
                           status VARCHAR(30) NOT NULL,
                           data_denuncia DATE NOT NULL DEFAULT CURRENT_DATE,

                           criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                           atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                           CONSTRAINT pk_denuncias PRIMARY KEY (id),

                           CONSTRAINT fk_denuncias_tutor
                               FOREIGN KEY (tutor_id)
                                   REFERENCES tutores(id)
                                   ON UPDATE CASCADE
                                   ON DELETE SET NULL,

                           CONSTRAINT ck_denuncias_tipo
                               CHECK (tipo_denuncia IN ('Maus-tratos', 'Abandono', 'Animal ferido', 'Outro')),

                           CONSTRAINT ck_denuncias_descricao_tamanho
                               CHECK (LENGTH(TRIM(descricao)) >= 10),

                           CONSTRAINT ck_denuncias_localizacao_tamanho
                               CHECK (LENGTH(TRIM(localizacao)) >= 3),

                           CONSTRAINT ck_denuncias_status
                               CHECK (status IN ('Recebida', 'Em análise', 'Em atendimento', 'Finalizada')),

                           CONSTRAINT ck_denuncias_data_valida
                               CHECK (data_denuncia <= CURRENT_DATE),

                           CONSTRAINT ck_denuncias_datas_validas
                               CHECK (atualizado_em >= criado_em)
);


CREATE TABLE resgates (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY,

                          tutor_id BIGINT,
                          especie VARCHAR(20) NOT NULL,
                          descricao TEXT NOT NULL,
                          localizacao VARCHAR(180) NOT NULL,
                          status VARCHAR(30) NOT NULL,
                          data_resgate DATE NOT NULL DEFAULT CURRENT_DATE,

                          criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                          CONSTRAINT pk_resgates PRIMARY KEY (id),

                          CONSTRAINT fk_resgates_tutor
                              FOREIGN KEY (tutor_id)
                                  REFERENCES tutores(id)
                                  ON UPDATE CASCADE
                                  ON DELETE SET NULL,

                          CONSTRAINT ck_resgates_especie
                              CHECK (especie IN ('Cachorro', 'Gato')),

                          CONSTRAINT ck_resgates_descricao_tamanho
                              CHECK (LENGTH(TRIM(descricao)) >= 10),

                          CONSTRAINT ck_resgates_localizacao_tamanho
                              CHECK (LENGTH(TRIM(localizacao)) >= 3),

                          CONSTRAINT ck_resgates_status
                              CHECK (status IN ('Solicitado', 'Em análise', 'Em atendimento', 'Finalizado', 'Cancelado')),

                          CONSTRAINT ck_resgates_data_valida
                              CHECK (data_resgate <= CURRENT_DATE),

                          CONSTRAINT ck_resgates_datas_validas
                              CHECK (atualizado_em >= criado_em)
);


CREATE INDEX idx_animais_especie
    ON animais(especie);

CREATE INDEX idx_animais_status
    ON animais(status);

CREATE INDEX idx_animais_especie_status
    ON animais(especie, status);

CREATE INDEX idx_adocoes_data
    ON adocoes(data_adocao);

CREATE INDEX idx_adocoes_status
    ON adocoes(status);

CREATE INDEX idx_adocoes_tutor
    ON adocoes(tutor_id);

CREATE INDEX idx_adocoes_animal
    ON adocoes(animal_id);

CREATE INDEX idx_castracoes_data
    ON castracoes(data_solicitacao);

CREATE INDEX idx_castracoes_especie
    ON castracoes(especie);

CREATE INDEX idx_castracoes_status
    ON castracoes(status);

CREATE INDEX idx_castracoes_especie_status
    ON castracoes(especie, status);

CREATE INDEX idx_denuncias_data
    ON denuncias(data_denuncia);

CREATE INDEX idx_denuncias_status
    ON denuncias(status);

CREATE INDEX idx_resgates_data
    ON resgates(data_resgate);

CREATE INDEX idx_resgates_status
    ON resgates(status);

COMMIT;